# -*- coding: utf-8 -*-
"""P5_APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-nxrjctUmTcEOj5DKIvE6_XNUiR_bJE
"""

!pip install gradio

!pip install requests

!pip install gradio_client

import gradio as gr
import joblib
loaded_model = joblib.load('/content/drive/MyDrive/DS/ENDTOEND_ML02ASSIGNMENT/houserent_model.pkl')
def predict(square_footage,num_bedrooms,house_age):
  result =  loaded_model.predict([[int(square_footage),int(num_bedrooms),int(house_age)]])
 # return 'prediction '


demo = gr.Interface(
    fn=predict,
    inputs=["text","text","text"],
    outputs=["text"],
    )
demo.launch(debug=True)